### ISSUE TITLE
Please tell me how to make utt2spk file. Please

### ISSUE THREAD

**Issue by saumyaborwankar** [iiscleap/self_supervised_AHC#1]
My current utt2spk file:
```
Bunny-aaaa-020125-020224-00000000-00000099 Bunny
Bunny-aaaa-021120-021414-00000000-00000150 Bunny
Bunny-aaaa-021120-021414-00000075-00000225 Bunny
Honey-aaaa-019827-020124-00000000-00000150 Honey
Honey-aaaa-019827-020124-00000075-00000225 Honey
Honey-aaaa-019827-020124-00000150-00000297 Honey
```
My current segments file:
```
Bunny-aaaa-020125-020224-00000000-00000099 aaaa 201.25 202.24
Bunny-aaaa-021120-021414-00000000-00000150 aaaa 211.2 212.7
Bunny-aaaa-021120-021414-00000075-00000225 aaaa 211.95 213.45
Honey-aaaa-019827-020124-00000000-00000150 aaaa 198.27 199.77
Honey-aaaa-019827-020124-00000075-00000225 aaaa 199.02 200.52
Honey-aaaa-019827-020124-00000150-00000297 aaaa 199.77 201.24
```
Is this wrong? What should be the second column in utt2spk? Should it be 'aaaa' (wavfile name) or should it be 'Honey' (character name).

**Comment by iiscleap** [comment]
utt2spk second column is generally speaker id (Honey in your case). But in diarization we don't know this information therefore we keep speaker id as file -id (aaaa in your case). May I know why are you creating it ? Because we will not know the speakers in the self-supervised training and testing.

**Comment by saumyaborwankar** [comment]
When we start the training we need the information (honey in second column - utt2spk) When we are testing we don't know which character is present (aaaa in second column - utt2spk). So when I'm training what should I keep as the second column?

Also I want to train it on my custom data so I am creating utt2spk and segments file myself.

**Comment by saumyaborwankar** [comment]
I'm getting this error when I changed my utt2spk to [utter-id file-id]. Any help?

```
Traceback (most recent call last):
  File "xvec_ahc_train.py", line 713, in <module>
    main()
  File "xvec_ahc_train.py", line 708, in main
    ahc_obj.train_with_threshold(model_init)
  File "xvec_ahc_train.py", line 423, in train_with_threshold
    check_clusterpurity(f, cluster, dataset,full_gndlist,labelfull)
  File "xvec_ahc_train.py", line 123, in check_clusterpurity
    if len(gnd_label[0][a])==1:
IndexError: list index out of range
```

**Comment by iiscleap** [comment]
Sorry I missed these comments. I will get back to you by EOD.
